import turtle as t
import numpy as np
t.speed(10)
def circle(r):
    n = 100
    a = r*2*(np.sin(np.pi/n))
    t.up()
    t.fd(r)
    t.lt(90)
    t.down()
    for i in range(n):
        t.fd(a)
        t.lt(360/n)
    t.up()
    t.lt(90)
    t.fd(r)
t.color("yellow")
t.begin_fill()
circle(100)
t.end_fill()
t.color("blue")
t.rt(45)
t.fd(70)
t.begin_fill()
circle(8)
t.end_fill()
t.fd(70)
t.lt(90)
t.fd(70)
t.begin_fill()
circle(8)
t.end_fill()
t.fd(70)
t.lt(45)
t.width(10)
t.color("black")
t.pendown()
t.fd(20)
t.penup()
t.fd(30)
t.color("red")
n = 50
t.pendown()
t.lt(90)
for i in range(30):
        t.fd(15*2*(np.sin(np.pi/n)))
        t.lt(2)
t.rt(180)
for i in range(60):
        t.fd(15*2*(np.sin(np.pi/n)))
        t.rt(2)
